[package]
name = "bitbox02-rust-c"
version = "0.1.0"
authors = ["Shift Cryptosecurity AG <support@shiftcrypto.ch>"]
edition = "2018"
license = "Apache-2.0"

[lib]
crate-type = ["staticlib"]

[profile.release]
debug = true
opt-level = 'z'
codegen-units = 1
panic = 'abort'
lto = true

[profile.dev]
opt-level = 'z'

[dependencies]
bitbox02-rust = { path = "../bitbox02-rust" }
bitbox02 = { path = "../bitbox02" }
util = { path = "../util" }
ethereum = { path = "../apps/ethereum", optional = true }
hex = { version = "0.4", default-features = false }
arrayref = "0.3.6"

[features]
# Only one of the "target-" should be activated, which in turn defines/activates the dependent features.
target-bootloader = ["bootloader", "platform-bitbox02"]
target-bootloader-development = ["bootloader", "platform-bitbox02"]
target-bootloader-development-locked = ["bootloader", "target-bootloader-development"]
target-bootloader-production = ["bootloader", "platform-bitbox02"]
target-bootloader-btc = ["bootloader", "platform-bitbox02"]
target-bootloader-btc-development = ["bootloader", "platform-bitbox02"]
target-bootloader-btc-production = ["bootloader", "platform-bitbox02"]
target-bootloader-bitboxbase = ["bootloader", "platform-bitboxbase"]
target-bootloader-bitboxbase-development = ["bootloader", "platform-bitboxbase"]
target-bootloader-bitboxbase-production = ["bootloader", "platform-bitboxbase"]
target-firmware = ["platform-bitbox02", "app-ethereum"]
target-firmware-btc = ["platform-bitbox02"]
target-firmware-bitboxbase = ["platform-bitboxbase"]
target-factory-setup = ["platform-bitbox02"]
target-factory-setup-bitboxbase = ["platform-bitboxbase"]
# add Rust features which are called in the C unit tests (currently there is only one target for C tests).
target-c-unit-tests = ["app-ethereum"]

platform-bitbox02 = []
platform-bitboxbase = []

bootloader = []

app-ethereum = [
  "ethereum", # this is a dependency
]
