dist: trusty

sudo: true

services:
  - docker

os:
  - linux

script:
# Pull the docker image as a separate step to measure the time it takes
- ./.ci/run-container-ci pull
- ./.ci/run-container-ci "${TRAVIS_BUILD_DIR}"

# Caching breaks the build right now because there is no dependency between the compiled external
# library and the placement in the `bin` directory.
#cache:
#  directories:
#    - build/external
#    - build-build/external
