language = "C"

include_guard = "BITBOX02_RUST_H"

include_version = true

[parse]
# Parse dependencies for types ...
parse_deps = true

# ... but only parse this crate.
include = ["bitbox02-rust"]

[export]
# malloc, free declared in bitbox02-rust-c/src/alloc.rs, but does not need to be exported, as it
# already exists in stdlib.h.
exclude = ["commander_bitboxbase", "malloc", "free"]
