language = "C"

include_guard = "COMMANDER_RUST_H"

include_version = true

includes = ["commander/commander.h", "bitboxbase.pb.h"]

[parse]
# Parse dependencies for types ...
parse_deps = true

# ... but only parse this crate.
include = ["bitbox02-rust"]
