[package]
name = "ethereum"
version = "0.1.0"
authors = ["Shift Cryptosecurity AG <support@shiftcrypto.ch>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
util = {path = "../../util"}
hex = { version = "0.4", default-features = false }
sha3 = { version = "0.8.2", default-features = false }
arrayref = "0.3.6"
