[package]
name = "ethereum"
version = "0.1.0"
authors = ["Shift Cryptosecurity AG <support@shiftcrypto.ch>"]
edition = "2018"

[dependencies]
util = {path = "../../util"}
sha3 = { version = "0.8.2", default-features = false }
