[package]
name = "bitbox02-rust"
version = "0.1.0"
authors = ["Shift Cryptosecurity AG <support@shiftcrypto.ch>"]
edition = "2018"
description = "BitBox02 functionality implemented in rust"
license = "Apache-2.0"

[lib]
# TODO: re-enable doctests. It currently fails with:
# "no global memory allocator found but one is required; link to std or add `#[global_allocator]` to a static item that implements the GlobalAlloc trait."
doctest = false

[dependencies]
bitbox02 = {path = "../bitbox02"}
binascii = "0.1"

# For stack allocated strings
[dependencies.arrayvec]
version  = "0.5.1"
# Disable the "std" feature
default-features = false
